# action.yml
name: "Alpine Raspberry Pi Builder"
description: "Produce an Alpine Linux image for Raspberry Pi"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
